Feature/groups
ogs-at-usi/handshake pull request #82
Opened 2022-12-14 11:24 UTC by JekxDevil

group feature added.
group list display to choose members need to be refactored in vuetify.
backend may need changes, see `TODO` notes related.

2022-12-15 00:06 UTC, micheledallerive commented
The chats are not sorted properly: if I have normal chats and group chats, the group chats are always at the bottom of the list.

2022-12-15 00:13 UTC, micheledallerive commented
The messages are not received right after the group chat is created. You need to refresh the page in order to make the messages work.

2022-12-15 00:16 UTC, micheledallerive commented
It is hard to understand what's the message and what is the sender (maybe adding the class `font-weight-bold` to the sender element class could help)

2022-12-15 00:17 UTC, micheledallerive commented
Tomorrow I am gonna refactor the group creation frontend page.

2022-12-16 13:10 UTC, JekxDevil commented
> It is hard to understand what's the message and what is the sender (maybe adding the class `font-weight-bold` to the sender element class could help)

fixed by @micheledallerive [7882fda](https://github.com/ogs-at-usi/handshake/pull/82/commits/7882fda4884129381e181f1868f27d8bea2f520c).

2022-12-16 13:32 UTC, JekxDevil commented
> The messages are not received right after the group chat is created. You need to refresh the page in order to make the messages work.

fixed by @JekxDevil [bfc1878](https://github.com/ogs-at-usi/handshake/pull/82/commits/bfc1878e6e441e0a6d79a549ccb4319514f15130).

2022-12-16 13:50 UTC, micheledallerive requested changes

2022-12-16 13:50 UTC, micheledallerive commented on client/src/plugins/api-client.js
> +    console.log('api create group:', group);
remove

2022-12-16 14:00 UTC, JekxDevil commented on client/src/plugins/api-client.js
> +    console.log('api create group:', group);
fixed [eded274](https://github.com/ogs-at-usi/handshake/pull/82/commits/eded274295911c696714c3f8cf0046e8a283fe0a).

2022-12-16 14:02 UTC, micheledallerive approved these changes

2022-12-16 14:32 UTC, DonnaDona approved these changes
:)

2022-12-16 14:43 UTC, merged